
❌ validate_tagged_players ERROR (2025-07-26 11:16:58 AM EDT):
Traceback (most recent call last):
  File "/home/runner/work/sports-betting-site/sports-betting-site/scripts/validate_tagged_players.py", line 2, in <module>
    from pydantic import BaseModel, ValidationError
ModuleNotFoundError: No module named 'pydantic'

---

❌ merge_data ERROR (2025-07-26 11:17:19 AM EDT):

---

