[FAIL] project_prep.py ERROR [2025-09-08 01:29:31 PM EDT]:
Traceback (most recent call last):
  File "/home/runner/work/baseball_for_mat/baseball_for_mat/scripts/project_prep.py", line 144, in <module>
    project_prep()
  File "/home/runner/work/baseball_for_mat/baseball_for_mat/scripts/project_prep.py", line 116, in project_prep
    merged = merged.merge(stadiums[venue_cols].drop_duplicates("team_id"),
  File "/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/pandas/core/frame.py", line 10839, in merge
    return merge(
  File "/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/pandas/core/reshape/merge.py", line 170, in merge
    op = _MergeOperation(
  File "/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/pandas/core/reshape/merge.py", line 807, in __init__
    self._maybe_coerce_merge_keys()
  File "/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/pandas/core/reshape/merge.py", line 1509, in _maybe_coerce_merge_keys
    raise ValueError(msg)
ValueError: You are trying to merge on int64 and object columns for key 'home_team_id'. If you wish to proceed you should use pd.concat

---

[FAIL] starter_coverage_guard.py ERROR [2025-09-08 01:29:35 PM EDT]:
Traceback (most recent call last):
  File "/home/runner/work/baseball_for_mat/baseball_for_mat/scripts/starter_coverage_guard.py", line 128, in <module>
    main()
  File "/home/runner/work/baseball_for_mat/baseball_for_mat/scripts/starter_coverage_guard.py", line 114, in main
    raise RuntimeError(
RuntimeError: Starter coverage failure: 4 starter(s) absent in pitcher_mega_z. See summaries/projections/mega_z_starter_coverage.csv and summaries/projections/mega_z_starter_missing.csv.

---

